# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('_asympcuts_rmvnorm', PACKAGE = 'asympcuts', nsamples, mean, covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('_asympcuts_dmvnorm', PACKAGE = 'asympcuts', x, mean, covariance)
}

